from __future__ import annotations

import os
import re
import subprocess
import threading

import core.state as s
from core.interpreter import project_python
from core.process import proj_run, program_name, program_version


def run_capture(cmd: list[str], timeout: int = s._BUILD_TIMEOUT) -> tuple[int, str]:
    try:
        out = subprocess.run(cmd, cwd=s._HERE, capture_output=True, text=True,
                             timeout=timeout, creationflags=s._NO_WINDOW)
        return out.returncode, (out.stdout + out.stderr)
    except (OSError, subprocess.SubprocessError) as e:
        return 1, str(e)


def iscc_path() -> str | None:
    if os.path.exists(s._ISCC_DEFAULT):
        return s._ISCC_DEFAULT
    import shutil
    return shutil.which("ISCC")


def default_iss(app: str, exe: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9]+", "", app) or "App"
    return f"""; Auto-generated by the ILX Launcher. Edit freely -- will NOT be overwritten.
#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif
#define AppName "{app}"
#define AppExe "{exe}"

[Setup]
AppName={{#AppName}}
AppVersion={{#AppVersion}}
DefaultDirName={{autopf}}\\{{#AppName}}
DefaultGroupName={{#AppName}}
OutputDir=Output
OutputBaseFilename={safe}-Setup-{{#AppVersion}}
Compression=lzma2
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64compatible

[Files]
Source: "..\\dist\\{{#AppName}}\\*"; DestDir: "{{app}}"; Flags: recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#AppName}}"; Filename: "{{app}}\\{{#AppExe}}"
Name: "{{commondesktop}}\\{{#AppName}}"; Filename: "{{app}}\\{{#AppExe}}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"

[Run]
Filename: "{{app}}\\{{#AppExe}}"; Description: "Launch {{#AppName}}"; Flags: nowait postinstall skipifsilent
"""


def ensure_iss() -> str | None:
    if os.path.exists(s._ISS):
        return s._ISS
    app = program_name() if program_name() != "ILX" else s._APP_NAME
    exe = f"{app}.exe"
    try:
        os.makedirs(os.path.dirname(s._ISS), exist_ok=True)
        with open(s._ISS, "w", encoding="utf-8") as f:
            f.write(default_iss(app, exe))
        print(f"[build] generated installer script -> {os.path.relpath(s._ISS, s._HERE)}")
        return s._ISS
    except OSError as e:
        print(f"[build] could not write {s._ISS}: {e}")
        return None


def pyinstaller_available() -> bool:
    import importlib.util
    py = project_python()
    if os.path.abspath(py) == os.path.abspath(__import__("sys").executable):
        try:
            return importlib.util.find_spec("PyInstaller") is not None
        except (ImportError, ValueError):
            return False
    try:
        out = subprocess.run([py, "-c", "import PyInstaller"],
                             capture_output=True, timeout=20, creationflags=s._NO_WINDOW)
        return out.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def ensure_pyinstaller() -> bool:
    if pyinstaller_available():
        return True
    if not s._config.get("auto_install_build"):
        s._build_overlay = "PyInstaller not installed (enable auto-install in Configuration)"
        return False
    s._build_overlay = "installing PyInstaller..."
    rc, log = run_capture([project_python(), "-m", "pip", "install", "pyinstaller"])
    if rc != 0 or not pyinstaller_available():
        s._build_overlay = "PyInstaller install FAILED - see launcher console"
        print("[build] pip install pyinstaller failed:\n" + log[-2000:])
        return False
    return True


def pyinstaller_cmd(mode: str) -> list[str]:
    py = project_python()
    if os.path.exists(s._SPEC):
        return [py, "-m", "PyInstaller", "--noconfirm", s._SPEC]
    flag = "--onefile" if mode == "onefile" else "--onedir"
    app  = program_name() if program_name() != "ILX" else s._APP_NAME
    return [py, "-m", "PyInstaller", "--noconfirm", "--windowed", flag, "--name", app, s._MAIN]


def bump_version(kind: str) -> str | None:
    path = os.path.join(s._HERE, "version.py")
    try:
        major, n, m = (int(x) for x in program_version().split("."))
    except ValueError:
        return None
    n2, m2 = (n, m + 1) if kind == "exe" else (n + 1, m + 1)
    new = f"{major}.{n2}.{m2}"
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
        text = re.sub(r'VERSION\s*=\s*"[^"]*"', f'VERSION = "{new}"', text, count=1)
        text = re.sub(r'VERSION_INFO\s*=\s*\([^)]*\)',
                      f"VERSION_INFO = ({major}, {n2}, {m2})", text, count=1)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
    except OSError:
        return None
    return new


def build_worker(make_installer: bool) -> None:
    from core.automation import quality_gate
    s._build_running  = True
    s._build_progress = 0.0
    try:
        if s._config.get("gate_before_build"):
            s._build_overlay = "quality gate (tests + lint + import)..."
            ok, report = quality_gate()
            if not ok:
                s._build_overlay = "build blocked - quality gate FAILED (see console)"
                print("[build] quality gate failed:\n" + report)
                return
        if not ensure_pyinstaller():
            return
        new = bump_version("installer" if make_installer else "exe")
        if not new:
            s._build_overlay = "version bump failed"
            return
        mode = str(s._config.get("build_mode", "onedir"))
        kind = "one-file" if mode == "onefile" else "one-folder"
        s._build_overlay  = f"v{new}: building EXE ({kind})..."
        s._build_progress = 0.3
        rc, log = run_capture(pyinstaller_cmd(mode))
        if rc != 0:
            s._build_overlay = "EXE build FAILED - see launcher console"
            print("[build] PyInstaller failed:\n" + log[-3000:])
            return
        if not make_installer:
            s._build_overlay  = f"v{new}: EXE built -> dist\\{s._APP_NAME}"
            s._build_progress = 1.0
            return
        iscc = iscc_path()
        if not iscc:
            s._build_overlay = "Inno Setup (ISCC.exe) not found - EXE built, installer skipped"
            return
        iss = ensure_iss()
        if not iss:
            s._build_overlay = "could not prepare an installer script - EXE built"
            return
        s._build_overlay  = f"v{new}: building installer (Inno Setup)..."
        s._build_progress = 0.7
        rc, log = run_capture([iscc, f"/DAppVersion={new}", iss])
        if rc != 0:
            s._build_overlay = "installer build FAILED - see launcher console"
            print("[build] ISCC failed:\n" + log[-3000:])
            return
        s._build_overlay  = f"v{new}: installer built -> installer\\Output"
        s._build_progress = 1.0
    finally:
        s._build_running = False


def build_exe() -> None:
    if s._build_running or s._manual_running:
        return
    s._build_thread = threading.Thread(target=build_worker, args=(False,), daemon=True)
    s._build_thread.start()


def build_installer() -> None:
    if s._build_running or s._manual_running:
        return
    s._build_thread = threading.Thread(target=build_worker, args=(True,), daemon=True)
    s._build_thread.start()
